package be.nisc.modelmappertools.api;

import java.io.Serializable;
import java.util.Objects;

public class FieldMapping implements Serializable {
    public String fromPath, toPath;
    public String fromAccessPath, toAccessPath;
    public String toType;
    public boolean autoGenerated;
    public boolean active;
    public String converter;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldMapping that = (FieldMapping) o;
        return Objects.equals(fromPath, that.fromPath) &&
                Objects.equals(toPath, that.toPath);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fromPath, toPath);
    }
}
