package be.nisc.modelmappertools.api;

import java.util.Arrays;

public class FieldMapping {
    public String fromPath[], toPath[];
    public String toType;
    public boolean autoGenerated;
    public boolean active;
    public String converter;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldMapping that = (FieldMapping) o;
        return Arrays.equals(fromPath, that.fromPath) &&
                Arrays.equals(toPath, that.toPath);
    }

    @Override
    public int hashCode() {

        int result = Arrays.hashCode(fromPath);
        result = 31 * result + Arrays.hashCode(toPath);
        return result;
    }
}
